### PR TITLE
Feature/sync upstream 2.21.0

### PR DESCRIPTION
**Pull request by YoshuaNava**

### CODE REVIEW

**Comment by YoshuaNava** [comment]
@jsburklund @maximilianwulf Could you have a look into this PR before we merge?

**Comment by maximilianwulf** [comment]
@YoshuaNava you mean running it on our computer?

**Comment by YoshuaNava** [comment]
> @YoshuaNava you mean running it on our computer?

Yes. As you regularly use the RealSense for your work, I thought it would make sense.

I'll run tests on the robot this Friday.

**Comment by maximilianwulf** [comment]
Okay, I will do it.

**Comment by raabuchanan** [comment]
Have you checked the performance difference? This should make my PR #14 unnecessary.

**Comment by YoshuaNava** [comment]
@raabuchanan Not yet. We have scheduled tests for tomorrow. Thanks for checking the performance variation in your PR, this gives us good insight about the influence of OpenMP on the driver's resource consumption.

**Comment by YoshuaNava** [comment]
I ran tests today, and the performance of the driver seems to be better. From around 7-10% CPU for the previous version, to 3-5%. Apart from that, it behaves in more or less the same way.

**Comment by maximilianwulf** [comment]
On my machine (Lenovo T480) the performance change is significant. 
In idle mode, the old node consumes 60% CPU power, this PR brings it down to 14%.
When running RVIZ and AprilTag, the old node used 140% and the new one uses 80%.

Very useful PR. Thank you!

**Comment by YoshuaNava** [comment]
> On my machine (Lenovo T480) the performance change is significant.
> In idle mode, the old node consumes 60% CPU power, this PR brings it down to 14%.
> When running RVIZ and AprilTag, the old node used 140% and the new one uses 80%.
> 
> Very useful PR. Thank you!

After reading this we verified together the performance of the node on our laptops. On the Lenovo P51 I'm using the node consumes between 3 and 5% of CPU. This is maybe related to throttling or CPU architecture differences.

**Pull request merged**
